vich_uploader:
    db_driver: orm

    mappings:
        entreprise_logo:
            uri_prefix: /images/entreprises
            upload_destination: '%kernel.project_dir%/public/images/entreprises'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
