controllers:
  resource: ../src/Controller/
  type: attribute
# config/routes.yaml
index:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
  defaults:
    route: 'app_freemium'