name: Deploy Symfony App
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          cd /home/HardWareHouse
          git pull
          docker compose exec php npm install
          docker compose exec php npm run build
          docker compose exec php bin/console d:m:m -n
